/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated.new'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated.library'
import { Route as AuthenticatedEnglishTestRouteImport } from './routes/_authenticated.english-test'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated.curriculum'
import { Route as AuthenticatedDeckDeckIdRouteImport } from './routes/_authenticated.deck.$deckId'
import { Route as AuthenticatedCurriculumLevelIdSubjectChapterIdxRouteImport } from './routes/_authenticated.curriculum.$levelId.$subject.$chapterIdx'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnglishTestRoute =
  AuthenticatedEnglishTestRouteImport.update({
    id: '/english-test',
    path: '/english-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeckDeckIdRoute = AuthenticatedDeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute =
  AuthenticatedCurriculumLevelIdSubjectChapterIdxRouteImport.update({
    id: '/$levelId/$subject/$chapterIdx',
    path: '/$levelId/$subject/$chapterIdx',
    getParentRoute: () => AuthenticatedCurriculumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/curriculum': typeof AuthenticatedCurriculumRouteWithChildren
  '/english-test': typeof AuthenticatedEnglishTestRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new': typeof AuthenticatedNewRoute
  '/deck/$deckId': typeof AuthenticatedDeckDeckIdRoute
  '/curriculum/$levelId/$subject/$chapterIdx': typeof AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/curriculum': typeof AuthenticatedCurriculumRouteWithChildren
  '/english-test': typeof AuthenticatedEnglishTestRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new': typeof AuthenticatedNewRoute
  '/': typeof AuthenticatedIndexRoute
  '/deck/$deckId': typeof AuthenticatedDeckDeckIdRoute
  '/curriculum/$levelId/$subject/$chapterIdx': typeof AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRouteWithChildren
  '/_authenticated/english-test': typeof AuthenticatedEnglishTestRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/deck/$deckId': typeof AuthenticatedDeckDeckIdRoute
  '/_authenticated/curriculum/$levelId/$subject/$chapterIdx': typeof AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/curriculum'
    | '/english-test'
    | '/library'
    | '/new'
    | '/deck/$deckId'
    | '/curriculum/$levelId/$subject/$chapterIdx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/curriculum'
    | '/english-test'
    | '/library'
    | '/new'
    | '/'
    | '/deck/$deckId'
    | '/curriculum/$levelId/$subject/$chapterIdx'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/curriculum'
    | '/_authenticated/english-test'
    | '/_authenticated/library'
    | '/_authenticated/new'
    | '/_authenticated/'
    | '/_authenticated/deck/$deckId'
    | '/_authenticated/curriculum/$levelId/$subject/$chapterIdx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/english-test': {
      id: '/_authenticated/english-test'
      path: '/english-test'
      fullPath: '/english-test'
      preLoaderRoute: typeof AuthenticatedEnglishTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deck/$deckId': {
      id: '/_authenticated/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof AuthenticatedDeckDeckIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/curriculum/$levelId/$subject/$chapterIdx': {
      id: '/_authenticated/curriculum/$levelId/$subject/$chapterIdx'
      path: '/$levelId/$subject/$chapterIdx'
      fullPath: '/curriculum/$levelId/$subject/$chapterIdx'
      preLoaderRoute: typeof AuthenticatedCurriculumLevelIdSubjectChapterIdxRouteImport
      parentRoute: typeof AuthenticatedCurriculumRoute
    }
  }
}

interface AuthenticatedCurriculumRouteChildren {
  AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute: typeof AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute
}

const AuthenticatedCurriculumRouteChildren: AuthenticatedCurriculumRouteChildren =
  {
    AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute:
      AuthenticatedCurriculumLevelIdSubjectChapterIdxRoute,
  }

const AuthenticatedCurriculumRouteWithChildren =
  AuthenticatedCurriculumRoute._addFileChildren(
    AuthenticatedCurriculumRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRouteWithChildren
  AuthenticatedEnglishTestRoute: typeof AuthenticatedEnglishTestRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDeckDeckIdRoute: typeof AuthenticatedDeckDeckIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRouteWithChildren,
  AuthenticatedEnglishTestRoute: AuthenticatedEnglishTestRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDeckDeckIdRoute: AuthenticatedDeckDeckIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
